### ISSUE TITLE
met some errors when set/get the same key frequently

### ISSUE THREAD

**Issue by zhanghan-mq** [etcd-cpp-apiv3/etcd-cpp-apiv3#167] opened 2022-09-29 02:10 UTC
code as bellow:
```
class etcd_store {
etcd::Client* _etcd;

// get_callback_func must have a "bool" argument
  template<typename set_func>
  void set_value(
    const std::string& key, const std::string& value, set_func&& set_callback_func) const {
    _etcd->set(key, value)
      .then([this, set_callback_func](pplx::task<etcd::Response> response_task) {
        etcd::Response response = response_task.get();
        set_callback_func(response.is_ok());
      });
  }
  // get_callback_func must have a "std::string" argument
  template<typename get_func>
  void get_value(const std::string& key, get_func&& get_callback_func) const {
    _etcd->get(key).then([this, get_callback_func](pplx::task<etcd::Response> response_task) {
      etcd::Response response = response_task.get();
      if (response.is_ok()) {
        get_callback_func(response.value().as_string());
      } else {
        get_callback_func("");
      }
    });
  }
};

BOOST_AUTO_TEST_CASE(test_store) {
  etcd::Client etcd("http://127.0.0.1:2379");
  store etcd_store(&etcd);
  std::string value("value-");
  std::string key("key-1");
  // use sync way to set the key firstly
  sync_set_func(etcd, key, value);

  for (int i = 0; i < TEST_COUNTS; i++) {
    etcd_store.set_value(key, value + "ab-", [](bool state) { BOOST_CHECK(state); }); // BOOST_CHECK(state)  met error
    etcd_store.get_value(key, [](std::string value) { BOOST_CHECK(value.length()); }); // BOOST_CHECK(value.length())  met error
  }
}
```
thanks

**Comment by sighingnow** [comment] 2022-09-29 02:56
The issue is caused by "etcdserver: too many requests" from the etcd server.

ETCD itself has a constant limit `maxGapBetweenApplyAndCommitIndex = 5000` which controls the maximum gap between committed index and applied index. When the gap is larger than the limit, the request will fail as a "etcdserver: too many requests" error.

Thus the `BOOST_CHECK(state)` failure is the expect / correct behaviour of the etcd server.

**Closed** 2022-09-29 02:56 UTC
Labels: bug, invalid

**Comment by zhanghan-mq** [comment] 2022-09-29 13:57
> The issue is caused by "etcdserver: too many requests" from the etcd server.
> 
> ETCD itself has a constant limit `maxGapBetweenApplyAndCommitIndex = 5000` which controls the maximum gap between committed index and applied index. When the gap is larger than the limit, the request will fail as a "etcdserver: too many requests" error.
> 
> Thus the `BOOST_CHECK(state)` failure is the expect / correct behaviour of the etcd server.

I try to print the error_massge as bellow:
```
    // get_callback_func must have a "bool" argument
    template<typename set_func>
    void set_value(
      const std::string& key, const std::string& value, set_func&& set_callback_func) const {
      _etcd->set(key, value)
        .then([this, set_callback_func](pplx::task<etcd::Response> response_task) {
          etcd::Response response = response_task.get();
          if(!response.is_ok()) // if met err, print
            std::cout << "error=====  " << response.error_message() << std::endl;
          set_callback_func(response.is_ok());
        });
    }
```
but it doesn't happend to print , because `response.is_ok() = true` , it still met error in `BOOST_CHECK(state)`
```
../src/test/test_master_etcd.cc(43): info:
```

**Comment by sighingnow** [comment] 2022-09-30 06:53
When `BOOST_CHECK(state)`, you must have a the message printed, I think.

**Comment by zhanghan-mq** [comment] 2022-09-30 08:39
> When `BOOST_CHECK(state)` fails, you must have a the message printed, I think.

You are right，I add TEST_COUNTS to 50000, then I meet the err.
Thanks
