### ISSUE TITLE
Get lease ttl and connection state for lock and keep-alive

### ISSUE THREAD

**Issue by pyssling** [etcd-cpp-apiv3/etcd-cpp-apiv3#49] opened 2021-03-29 11:28 UTC
I'm trying to understand how to get the lease TTL for a lock, and also ideally a callback on lease expiry. This happens for example during a network partition or an etcd failover.

Specifically I would want the following:
- Whether a lease has expired for a lock? (TTL = -1 on the keep-alive I believe)
- Whether the keep-alive connection has failed?

All help much appreciated!

**Comment by sighingnow** [comment] 2021-03-30 05:19
The lease and lock works in the following ways:

+ Use lease

Lease itself has nothing to do with lock. A lease create be created and destroyed using `client.leasegrant(int ttl)` and `client.leaserevoke(int64_t lease_id)`, respectively.

The remaining TTL for a lease could be obtained using `client.leasetimetolive(int64_t lease_id)`. To obtain a such callback for expiry, you could first get the remaining TTL and then setup such a async timer.

The `etcd::KeepAlive` class encapsules fixed-rate "keepalive" request into a class, behind the screen there is a background thread to refersh the lease again and again to make it "alive". For `KeepAlive` the lease won't expire until being cancelled.

+ Use lock

For locks users have two options about the setup of the lease, if a lease_id is provided, it is the user's responsility to make sure the lease is alive, otherwise there will be automatically a `KeepAlive` instance to make sure the lock is valid.

Specifically for your questions,

> Whether a lease has expired for a lock? (TTL = -1 on the keep-alive I believe)

Use `client.leasetimetolive(int64_t lease_id)`.

> Whether the keep-alive connection has failed?

If the grpc requests fails (e.g., the etcd server is done), there will be an exception ( https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/src/v3/AsyncLeaseAction.cpp#L108 ).

**Comment by pyssling** [comment] 2021-03-30 09:51
Ok, so if I understand things right:

The lock uses a lease and a lock is held as long as the lease is active: https://etcd.io/docs/v3.4/dev-guide/api_concurrency_reference_v3/

So in order to monitor the lease associated with a lock I need to manually create a lease, which I pass to the lock method. Then I need setup a timer to refresh the lease regularly.

Is there any method provided to refresh leases (outside of the KeepAlive) or should I use my own KeepAlive object which I can then monitor to check that it is maintaining the lease properly?

**Comment by sighingnow** [comment] 2021-03-30 09:54
> Is there any method provided to refresh leases (outside of the KeepAlive)

I could add such a method to client.

**Comment by sighingnow** [comment] 2021-03-30 10:00
> > Is there any method provided to refresh leases (outside of the KeepAlive)
> 
> I could add such a method to client.

I have just recalled that the missing of "client.keepalive" is by design. The grpc interface for `KeepAlive` is in stream fashion:

```proto
  // LeaseKeepAlive keeps the lease alive by streaming keep alive requests from the client
  // to the server and streaming keep alive responses from the server to the client.
  rpc LeaseKeepAlive(stream LeaseKeepAliveRequest) returns (stream LeaseKeepAliveResponse) {
      option (google.api.http) = {
        post: "/v3/lease/keepalive"
        body: "*"
    };
  }
```

Thus it would be inefficient to use a ping style keep alive (i.e., construct a bidirectional stream but use it just for once)..

So you could use a `KeepAlive` object to maintain the lease.

**Comment by pyssling** [comment] 2021-03-30 10:08
Good. I'll try this out. A question regarding the exception if there is a disconnect - it would be thrown on the KeepAlive thread right?

**Comment by sighingnow** [comment] 2021-04-02 08:02
> Good. I'll try this out. A question regarding the exception if there is a disconnect - it would be thrown on the KeepAlive thread right?

When disconnect happens, unfornately the exception is throwed in another pplx thread, rather than the KeepAlive thread. That is bad, and I'm considering to add something like a callback or a `check()` method on keepalive to let users could retrieve the exception.

**Comment by pyssling** [comment] 2021-04-02 08:30
That would be most helpful! Thank you.

**Comment by sighingnow** [comment] 2021-04-02 09:06
> That would be most helpful! Thank you.

Has been implementation in #53, please refer the new added documentation in that pull request for more details.

Note that for the handler case, the handler will be invoked in a separated thread, rather than the thread where the `KeepAlive` instance is created, but that should be enough for your case.

**Closed** 2021-04-02 09:15 UTC
Labels: question
